from scrapy.selector import Selector


sentences = [
	"Owing to the fact that the conditions were icy, the two cars collided, causing significant delays.",
	"The court case was initiated because of allegations published in a newspaper, sparking legal action.",
	"The problem with pollution in urban areas is becoming increasingly severe.",
	"The situation in our cities with regard to traffic is becoming untenable due to congestion.",
	"We must work together to find a solution to the dilemma of renewable energy adoption.",
	"Your claim that technology only has negative impacts is quite one-sided.",
	"Our company's position with regard to environmental sustainability is firm and proactive.",
	"The current water crisis demands innovative solutions for conservation and management.",
	"The evaluation of the solution to the housing crisis highlighted its potential and challenges.",
	"In parenthesis, let us not forget that every small contribution counts towards our goal.",
	"The time-consuming writing of reports often detracts from his ability to focus on other tasks.",
	"The loud burglar alarm alerted the neighbors to the attempted break-in.",
	"Starting the new business was a leap of faith, but it paid off in the end.",
	"Finding that rare book at the garage sale was a stroke of luck.",
	"In winter, a warm jacket is the most useful article of clothing you can have.",
	"He finally decided to tackle the growing pile of clothes in his laundry room.",
	"After cleaning the garage, they had a sack of rubbish ready for disposal.",
	"She used a pair of scissors to cut the fabric for her sewing project.",
	"He went out to do the shopping for the week.",
	"It's easy to be taken in by his charm and end up believing everything he says.",
	"It seems like he takes her for granted, never appreciating her efforts.",
	"He seems cranky; maybe he got out of bed on the wrong side today.",
	"The speaker got off to a good start with his speech, capturing the audience's attention immediately.",
	"He's plotting to get his own back on her somehow for the prank she played on him.",
	"They spent the evening setting the world to rights over a few drinks.",
	"After hearing the rumors, she was able to put two and two together and figure out the truth.",
	"He covered the basic needs of shelter, food, and water during his survival training.",
	"Employees are promoted on the basis of their performance and dedication.",
	"She forgot her mobile at home and felt disconnected all day.",
	"Avoid the boss today; he's like a bear with a sore head.",
	"By being mindful of small expenses, you'll find that the larger sums will accumulate; take care of the pennies and the pounds will take care of themselves.",
	"Any trespassers found on the property will be prosecuted.",
	"Drivers are advised to reduce speed now due to the road conditions.",
	"In this parking area, you must pay and display your ticket on the dashboard.",
	"Please place your purchases here before proceeding to the checkout counter.",
	"The community decided to back the local sports team by attending all their games.",
	"The drama of the situation escalated as tensions rose among the team members.",
	"Surviving the natural disaster was an ordeal for the entire community.",
	"The government launched a probe into the alleged corruption within the agency.",
	"The party had a fancy dress theme, so everyone came in elaborate costumes.",
	"Networking at professional events can lead to valuable connections and opportunities.",
	"The city's skyline is dominated by high-rise blocks of apartments.",
	"To apologize for the delay, the restaurant offered dessert on the house.",
	"During the meeting, he was confronted with some uncomfortable home truths about his performance.",
	"The documentary's message about environmental conservation is really hitting home.",
	"Working two jobs and raising a family, she felt she was leading a dog's life.",
	"You can find a variety of affordable fashion on the High Street.",
	"Off-the-rack clothing is convenient for those who need a quick fashion fix.",
	"She always dresses in the very latest fashion, keeping up with the newest trends.",
	"The designer's innovative use of materials set a new trend in the fashion industry.",
	"The hotel offers a no-frills accommodation option for budget travelers.",
	"The strict regulations put the creative team in a straitjacket, limiting their ability to innovate.",
	"The magician always has a trick up his sleeve to amaze the audience.",
	"Volunteering at the animal shelter has been a rewarding experience for her.",
	"Gardening has been a therapeutic hobby for her, helping her relax and de-stress.",
	"The sound of the ocean waves has a calming effect on her mind.",
	"She's a dabbler in various hobbies, from painting to playing the guitar.",
	"The support group is a safe space for recovering alcoholics to share their experiences.",
	"He moved into sheltered accommodation where he receives the support he needs.",
	"Friends and family gathered for a wake to remember and celebrate his life.",
	"The whole family wore black in mourning for their patriarch.",
	"The service was held at the crematorium, followed by a gathering at the family home.",
	"Her ashes were scattered across her favorite mountain, in a private ceremony.",
	"She believed that after death, one passes over to another realm.",
	"Her scornful remarks about the project demoralized the team.",
	"The officious behavior of the new manager is alienating the staff.",
	"Her pretentious speech was filled with obscure references to impress her audience.",
	"The debate devolved into puerile insults, disappointing the audience.",
	"The report was sloppy and full of errors, reflecting poorly on our team.",
	"Distraught over the loss, he found it hard to focus on work.",
	"They offered concessions to placate him and avoid further disagreements.",
	"The counselor worked hard to conciliate between the two feuding families.",
	"They considered offering territory to appease the enemy and end the conflict.",
	"The implacable hatred between the two rivals poisoned the atmosphere at every meeting.",
	"After winning the championship, the team was in an exultant mood.",
	"The community rejoiced at the safe return of the missing child.",
	"Jubilant shouts filled the stadium as the winning goal was scored.",
	"She felt on top of the world after her proposal was accepted.",
	"Talking about colleagues behind their backs can damage workplace relationships.",
	"They became partners in the venture, sharing both risks and rewards.",
	"Her honest feedback helped improve the project significantly.",
	"Being truthful in all dealings is a principle he never compromises on.",
	"The business partners had a falling out over the direction of the company.",
	"Being dishonest with his partners eventually led to the breakup of their business.",
	"She became distant towards her colleagues after the promotion, changing the team dynamic.",
	"He was scrupulously honest in all his financial dealings, earning him a good reputation.",
	"The leader demanded complete and unswerving loyalty from his followers.",
	"In every business venture, she was his staunchest ally, supporting him through thick and thin.",
	"Communication between them started to break down, leading to frequent misunderstandings.",
	"A genuine misunderstanding about the meeting time caused the mix-up.",
	"After the argument, they were on bad terms for weeks.",
	"Their once happy partnership turned sour due to financial disputes.",
	"They've had a bumpy relationship, marked by frequent arguments and reconciliations.",
	"Even in a crowded room, he only has eyes for her.",
	"She is completely besotted with her niece, spoiling her at every opportunity.",
	"They share a deep platonic relationship, valuing their friendship above all.",
	"They are kindred spirits, sharing a unique understanding and empathy towards each other.",
	"As partners, they are well-matched, complementing each other's strengths and weaknesses.",
	"Her adoring gaze whenever he speaks is a testament to her deep affection.",
	"He remained faithful to his childhood dream of becoming a pilot, pursuing it relentlessly.",
	"Their loyalty to each other was unshakeable, standing strong through various trials.",
	"The scrawny cat in the alley seemed to have been lost for weeks.",
	"The obese dog struggled to keep up during the walk.",
	"She always looks impeccable, never a hair out of place.",
	"His eye started twitching due to stress.",
	"He started tapping his fingers on the table, showing his impatience.",
	"Her conservative views are evident in her cautious approach to change.",
	"His methodical work habits ensure high-quality results.",
	"His stubborn refusal to compromise complicated the negotiation.",
	"She's very affectionate with her friends, always giving hugs.",
	"She's popular at school because of her friendly nature.",
	"Her intuitive understanding of the problem led to a quick solution.",
	"His stingy habits frustrate his friends when it comes to splitting bills.",
	"Her diligent preparation for exams always pays off.",
	"He values his independent lifestyle and makes his own decisions.",
	"Her placid demeanor helps calm those around her.",
	"His selfish actions often disregard the feelings of others.",
	"Her cunning strategy outmaneuvered the competition.",
	"His over-anxious nature sometimes hinders his ability to enjoy the moment.",
	"His magnetic personality attracts people wherever he goes.",
	"She's known to be good company, making her a favored guest at parties.",
	"His distrustful nature makes it hard for him to form close relationships.",
	"Her industrious efforts were key to the project's success.",
	"She's always supportive, offering help and encouragement to her friends.",
	"Her extravagant lifestyle is evident in her lavish spending habits.",
	"His down-to-earth attitude makes him relatable to everyone.",
	"Her altruistic efforts in the community have made a significant impact.",
	"His intellectual pursuits have earned him respect in the academic community.",
	"Her tolerant attitude towards differing opinions fosters open discussion.",
	"The salesman's hard sell technique turned off many potential buyers.",
	"Before making a major purchase, it's wise to shop around for the best deals.",
	"The new gadget is priced competitively to attract young buyers.",
	"They found success by targeting a niche market with specialized products.",
	"A positive workplace culture significantly contributes to employee well-being.",
	"Effective teamwork leads to the successful completion of projects.",
	"She thrives in the fast-moving environment of a startup.",
	"The dynamic nature of the tech industry keeps professionals constantly engaged.",
	"Without proper recognition, employees can become demotivated.",
	"Graduates often look to work in industries that offer the most innovation.",
	"Many young professionals seek a career in renewable energy due to its growth potential.",
	"The company offers generous maternity leave benefits to support new mothers.",
	"He took paternity leave to spend time with his newborn.",
	"Adoption leave is provided to parents to bond with their newly adopted child.",
	"The benefits package includes health insurance and holiday entitlement.",
	"All employees are covered by the company's health insurance plan.",
	"Her holiday entitlement allows for three weeks of paid vacation per year.",
	"Salary increments are based on performance evaluations.",
	"Her annual bonus is performance-related, reflecting her contributions to the team.",
	"Employees look forward to the annual bonus as a recognition of their hard work.",
	"Feeling overworked, she decided to talk to her manager about reducing her hours.",
	"The company offered voluntary redundancies to reduce its workforce.",
	"Compulsory redundancies were announced as part of the company's restructuring.",
	"During the holidays, the office operates with a skeleton staff to keep essential services running.",
	"She regularly meets with her opposite number in the partner company to discuss collaboration.",
	"Maintaining a good working relationship with colleagues is key to a harmonious office environment.",
	"She discussed the new contract terms with her counterpart from the other company.",
	"He quickly built a strong rapport with his new team, fostering an environment of trust.",
	"Employees who take the initiative often find more opportunities for advancement.",
	"The company's hierarchical structure sometimes impedes fast decision-making.",
	"Understanding the pecking order is crucial for new employees to navigate the office politics.",
	"They opted for a job-share arrangement to balance work and personal life.",
	"Hot-desking encourages flexibility and collaboration among employees.",
	"The team worked overtime to meet the deadline for the project submission.",
	"Working with children is challenging, but incredibly rewarding.",
	"The job felt mechanical after a while, with little room for creativity.",
	"Completing a project on time and under budget is deeply satisfying.",
	"The monotonous nature of the assembly line work led to employee dissatisfaction.",
	"Navigating the challenges of a rapidly changing market is both demanding and rewarding.",
	"The fashion industry may seem glamorous, but it requires hard work and dedication.",
	"Freelancers often have irregular working hours, adjusting their schedules to meet deadlines.",
	"The demands of her job led to an anti-social schedule, affecting her social life.",
	"The mind-numbing repetition of the task made it difficult to stay focused.",
	"The project team is working on tight schedules to meet the launch date.",
	"Feeling stuck in a rut, she decided to pursue further studies to advance her career.",
	"She went in with a start-up, excited by the potential for innovation.",
	"As a freelance designer, he enjoys the freedom to choose his projects.",
	"She did a trial run to the office to estimate her commute time.",
	"Practicing your interview answers can significantly boost your confidence.",
	"Making eye contact during the interview shows confidence and interest.",
	"A firm handshake at the beginning of the interview sets a confident tone.",
	"Could you talk us through your process for completing a project under tight deadlines?",
	"The company prefers to handle most projects in-house to maintain control over quality.",
	"The company is looking to take on experienced software developers to enhance the team.",
	"We aim to fill the post by next month to keep the project on schedule.",
	"Given your background, you seem to be an ideal fit for our team's dynamic.",
	"The reporting structure requires you to report directly to the senior manager.",
	"A passion for innovative solutions is what we look for in candidates.",
	"The role is challenging, but it offers significant opportunities for growth.",
	"Our office environment is fast-paced, requiring quick adaptation from our team.",
	"In this role, you'll be reporting to the head of the department.",
	"Previous experience in a similar role will be highly beneficial for this position.",
	"This role offers excellent career prospects for advancement within the company.",
	"Our comprehensive benefits package includes health insurance, paid vacations, and a retirement plan.",
	"The company offers subsidised gym memberships to promote employee wellness.",
	"During the interview, you may be asked about your salary expectations for the role.",
	"To stand out in your job application, tailor your cover letter to highlight your unique skills.",
	"My managerial experience and customer service skills underline my suitability for the managerial position.",
	"The team worked overtime in support of finishing the project before the deadline.",
	"She applied for the position of marketing director after five years in the marketing field.",
	"The role requires a hands-on approach to managing projects and leading teams.",
	"With ten years of experience in the field of digital marketing, she's considered an expert.",
	"His previous role involved extensive customer-facing interactions, enhancing his communication skills.",
	"Being a team player is essential in our collaborative work environment.",
	"Her managerial experience includes overseeing a department of 50 employees.",
	"Selective schooling systems often face criticism for promoting elitism and inequality.",
	"Comprehensive schooling aims to provide an equal educational opportunity to all students, regardless of their background.",
	"The debate around elitism in education focuses on the balance between meritocracy and accessibility.",
	"Certain biases are inherent in the selection process of elite institutions.",
	"League tables often influence parents' decisions when choosing schools for their children.",
	"The system tends to perpetuate inequalities between different social classes.",
	"The two-tier system in education creates a divide between well-funded and under-resourced schools.",
	"The public often perceives selective schools as offering a superior education.",
	"Bursaries are awarded based on financial need, supporting students to cover their educational expenses.",
	"The rise in tuition fees has sparked debates about the accessibility of higher education.",
	"Curriculum reform is underway to better equip students for the challenges of the 21st century.",
	"The syllabus for the course has been updated to include more current topics.",
	"Special needs education ensures that all students have access to personalized learning opportunities.",
	"One-to-one tutoring provides individualized attention to help students overcome specific learning challenges.",
	"His ability to solve complex mathematical problems quickly was considered a sign of genius.",
	"While rote-learning can help with memorization, it doesn't always lead to a deep understanding of the material.",
	"She used mnemonics to remember complex scientific terms.",
	"During exam season, he would bury himself into his books to prepare thoroughly.",
	"She studied intensively in the weeks leading up to her exams to cover all the topics.",
	"The essay on global warming challenged students to propose viable solutions to the crisis.",
	"The group project focused on designing an environmentally friendly product.",
	"For his final assessment, he submitted a portfolio of his photographic work.",
	"After completing the first draft of his report, he sought feedback from his peers.",
	"In her thesis, she acknowledged all the sources she used for her research.",
	"Once submitted, the essays are assessed by a team of faculty members.",
	"Feedback on the presentation was provided immediately, highlighting areas for improvement.",
	"If the book you need isn't available, you can request it through an inter-library loan.",
	"Open educational resources provide free access to educational materials for students and teachers.",
	"Studying for the finals requires discipline and a well-organized study plan.",
	"The program aims to produce well-qualified graduates who are ready to enter the workforce.",
	"If you're in town this weekend, be our guest for dinner.",
	"On their anniversary, they were wined and dined at an exclusive restaurant.",
	"The sluggish service at the cafe made them regret choosing it for the meeting.",
	"His sullen response to the feedback took everyone by surprise.",
	"The waiter's off-putting attitude made them decide not to return to the restaurant.",
	"After deciding to lead a healthier lifestyle, she began to count the calories in her meals.",
	"She allowed herself a small portion of dessert as a treat for her dietary discipline.",
	"Being a fussy eater, she found it challenging to find suitable options at the buffet.",
	"The restaurant accommodates all dietary requirements, including vegan and gluten-free options.",
	"At the picnic, everyone had to take pot luck since we all brought different dishes.",
	"She focuses on preparing wholesome meals that are nutritious and satisfying.",
	"Incorporating wholefoods into your diet can lead to better health outcomes.",
	"Avoiding foods with preservatives can lead to a cleaner, more natural diet.",
	"Restaurants are increasingly accommodating customers with food allergies by offering detailed menu information.",
	"Restaurants are expanding their menus to include more options for vegans.",
	"Animal welfare concerns have led to higher standards in livestock management.",
	"The ethical issues surrounding battery-farming are sparking debates on animal rights.",
	"Nutrition labels play a crucial role in helping consumers make informed food choices.",
	"Traffic-light labelling simplifies the process of identifying healthy food options.",
	"Fair trade practices ensure that producers in developing countries receive a fair price for their goods.",
	"After the argument, he was left to stew in his own juice, regretting his harsh words.",
	"The candidate was grilled by the interview panel on various complex topics.",
	"The blurb on the back cover provided a tantalizing glimpse into the book's plot.",
	"The artist's latest work was critically acclaimed and received several awards.",
	"The lugubrious tone of the novel perfectly captured the somber theme.",
	"The short story's macabre twist at the end took readers by surprise.",
	"The chilling narrative of the ghost story left listeners uneasy long after it was over.",
	"The film's gripping storyline kept audiences on the edge of their seats throughout.",
	"The novel's enigmatic ending left readers pondering the characters' true fates.",
	"The breathtaking views described in the travel journal inspired many to visit the remote island.",
	"His memoirs are filled with wry observations about life in the theatre.",
	"The evocative imagery in her poetry transports readers to a bygone era.",
	"The eponymous protagonist of the novel, 'Jane Eyre', is a character of great complexity and strength.",
	"The lecturer's engaging presentation style made complex topics accessible to all students.",
	"Her travel journal was filled with notes and sketches from her journey across Asia.",
	"In his memoirs, he recounts the challenges and triumphs of his life in politics.",
	"The encyclopedia offers a wealth of information on topics ranging from history to science.",
	"The camera came with a detailed manual to guide users through its many features.",
	"Her latest novel is a 'can't put down' kind of book, ideal for a long flight.",
	"The documentary was highly informative, offering new insights into the subject.",
	"The invention was ahead of its time, introducing concepts that were only appreciated years later.",
	"The book was a lightweight read, perfect for relaxing on a sunny afternoon.",
	"It took me a few chapters to really get into the novel, but then I couldn't put it down.",
	"Impressionism revolutionized the art world with its emphasis on light and color over precise details.",
	"Critics dismissed his early work as that of a mere dauber, but he later gained recognition as a master.",
	"The project was deemed a success by the stakeholders, exceeding all expectations.",
	"Over time, society has become inured to the shock value of controversial artworks.",
	"Her approach to the canvas was original, breaking away from traditional techniques to create something entirely new.",
	"The plot of the movie was predictable, with viewers able to guess the ending halfway through.",
	"The gallery's highbrow exhibition catered to a niche audience with a keen interest in avant-garde art.",
	"The comedian's lowbrow humor appealed to those looking for easy laughs without much depth.",
	"The philosopher's dense text was impenetrable, requiring multiple readings to grasp its meaning.",
	"The author's message was transparent, making it easy for readers to understand the themes of the book.",
	"The artist's sophisticated use of light and shadow brought a lifelike quality to the portrait.",
	"The sculpture's primitive style harkened back to ancient art forms, emphasizing raw and elemental beauty.",
	"The puzzle was challenging, designed to test the solver's wit and patience to the fullest.",
	"The dancer's dazzling performance captivated the audience, leaving them spellbound with her grace and agility.",
	"The novel's plot was criticized for being pedestrian, lacking the creativity and depth found in the author's earlier works.",
	"The painter's evocative landscapes evoke a sense of nostalgia, transporting viewers to picturesque rural scenes.",
	"The documentary was thought-provoking, raising important questions about environmental conservation.",
	"The art exhibit was unstimulating, with most pieces failing to evoke any strong emotional response from the visitors.",
	"The chef's exquisite dish was a harmonious blend of flavors that delighted the palate.",
	"The novice painter's clumsy attempt at a portrait resulted in an unrecognizable depiction of the subject.",
	"The mysterious novel presented an intriguing puzzle that readers were eager to solve.",
	"The dreary weather mirrored her mood, as she pondered over the day's events.",
	"The movie was just another run-of-the-mill romantic comedy that offered nothing new to the genre.",
	"His tongue-in-cheek remarks often amused his friends, who appreciated his dry sense of humor.",
	"Her earnest efforts to improve community health were recognized with a prestigious award.",
	"The counterfeit paintings, initially believed to be valuable, were later discovered to be worthless.",
	"The restoration of the painting was poorly done, resulting in damage to the original artwork.",
	"The play of light and shadow in his photographs adds depth and dimension to the images.",
	"The artist's use of shadowy figures in her paintings creates an atmosphere of mystery and intrigue.",
	"The details of the plan were sketchy, leaving many questions unanswered.",
	"The festival is known for its colourful costumes and lively music, attracting visitors from all over.",
	"The artist moulded the clay into a stunning sculpture, capturing the essence of human emotion.",
	"The photographer captured an image that perfectly conveyed the tranquility of the early morning.",
	"The documentary aimed to illuminate the complexities of the political situation in the region.",
	"The script was filled with hackneyed phrases that did little to engage the audience.",
	"The narrative felt disjointed, with scenes jumping abruptly without clear transitions.",
	"The movie's plot was far-fetched, stretching the limits of believability to the breaking point.",
	"The comedian's risque jokes pushed the envelope, eliciting mixed reactions from the crowd.",
	"The thriller was so gripping that viewers couldn't look away, even during the most intense scenes.",
	"The concert was a memorable experience, with performances that left an indelible mark on the audience.",
	"The lecture dragged on in a tedious manner, covering well-trodden ground without offering new insights.",
	"The play was hilarious, filled with witty dialogue and comedic situations that kept the audience laughing throughout.",
	"The band's performance was so energetic that the crowd demanded encores, not wanting the night to end.",
	"At the conclusion of the play, the cast received a standing ovation, a testament to their exceptional talent.",
	"The up-and-coming artist's exhibit attracted attention from galleries and collectors alike, signaling a promising career ahead.",
	"Her latest painting, considered a masterpiece, brilliantly captured the complexity of human emotions.",
	"After playing the villain in several films, the actor found himself typecast, struggling to secure different roles.",
	"The sequel was panned by critics, who found it uninspired compared to the original.",
	"The playwright was lauded for her innovative approach to storytelling, breathing new life into traditional narratives.",
	"The performance was booed by the audience, a clear sign of their dissatisfaction with the production.",
	"The lead actor was miscast, unable to convincingly portray the complexity of the character.",
	"Her unconvincing performance failed to connect with the audience, leaving much to be desired.",
	"He impressed the directors at the audition with his remarkable range and emotional depth.",
	"During rehearsals, the cast worked tirelessly to perfect their timing and chemistry.",
	"Her unique interpretation of the classic role brought a fresh perspective to the well-known character.",
	"The latest version of the musical included new songs that added depth to the storyline.",
	"His portrayal of the historical figure was both accurate and compelling, earning him critical acclaim.",
	"Archaeologists recently uncovered relics that shed new light on ancient civilizations.",
	"The exhibition explored the rise and fall of empires, highlighting their contributions to modern society.",
	"The dynasty's reign was marked by significant advances in art and science, leaving a lasting legacy.",
	"The dawn of the industrial age transformed societies, ushering in new technologies and ways of life.",
	"The reigns of various monarchs are chronicled in the history books, each contributing uniquely to the kingdom's legacy.",
	"The heirs to the throne were carefully groomed in the arts of leadership and governance.",
	"The king's successors continued his work, further strengthening the kingdom's position in the region.",
	"The empire expanded through a series of conquests, each adding new territories to its domain.",
	"Ancient manuscripts reveal insights into the daily lives and beliefs of people from past civilizations.",
	"Peasants formed the backbone of the agricultural economy, toiling on the land to produce the majority of the food supply.",
	"Labourers played a critical role in the construction of monumental architecture, from pyramids to cathedrals.",
	"Mass migrations have historically been triggered by factors such as war, famine, and the search for better opportunities.",
	"Archaeologists pieced together shreds of pottery to reconstruct ancient artifacts, gaining insight into past cultures.",
	"The artist's work was heavily influenced by the Renaissance.",
	"The Spanish galleon carried treasure from the New World.",
	"The slave worked in the fields from dawn to dusk.",
	"The ruler implemented new laws to improve the kingdom.",
	"The monarch decreed a national holiday in celebration.",
	"The nobility played a crucial role in governance.",
	"Orthography deals with the correct way of writing words.",
	"Ideograms represent ideas through symbols.",
	"The CEO gave a succinct presentation that highlighted the key points.",
	"The author's use of the mot juste gave the sentence a perfect clarity.",
	"Overwhelmed by emotion, he became inarticulate.",
	"The surprise left her speechless and unable to respond.",
	"The dinner had a celebratory atmosphere following the team's victory.",
	"The fireworks show was a stunning spectacle that lit up the night sky.",
	"The village prepared a lavish feast to celebrate the harvest.",
	"Feasting continued into the night, with music and dancing.",
	"The ceremonies included traditional dances and songs.",
	"The spring festival marked a renewal of life and spirit.",
	"The community renews its commitment to peace every year.",
	"The town has a sense of renewed vigor after the annual clean-up.",
	"The villagers are superstitious about the old well in the forest.",
	"The city celebrated its centenary with a series of events.",
	"The candlelit dinner created an atmospheric setting.",
	"The company's adherence to quality has won it numerous awards.",
	"He decided to convert to vegetarianism for health reasons.",
	"His fanatical devotion to the cause is well-known.",
	"His radicalism was evident in his revolutionary ideas.",
	"The group seeks to radicalise young people through social media.",
	"He didn't react well to the criticism.",
	"They seek to improve the community through volunteer work.",
	"The program aims to eradicate poverty in the region.",
	"She campaigned for environmental awareness in her community.",
	"Civil disobedience was used as a tactic to protest unjust laws.",
	"The resistance movement grew stronger despite government crackdowns.",
	"She gave him an incredulous look when he explained the story.",
	"The scam targets gullible individuals who easily trust others.",
	"His alibi sounded plausible to the police.",
	"The theory was dismissed as implausible by the experts.",
	"Sniffer dogs are used at airports to detect drugs and explosives.",
	"The country has seen an influx of refugees fleeing conflict.",
	"Many refugees claim asylum upon reaching a safe country.",
	"Asylum-seekers face long processing times for their applications.",
	"The police enforce the law to maintain public order.",
	"The policy of stop and search has been criticized for being discriminatory.",
	"Safety cameras are installed to catch drivers exceeding the speed limit.",
	"Exceeding the speed limit can result in hefty fines.",
	"Traffic wardens are responsible for issuing parking tickets.",
	"The security forces were deployed to maintain order during the protest.",
	"Undercover police infiltrate criminal groups to prevent illegal activities.",
	"The drug squad successfully dismantled a large narcotics network.",
	"The anti-corruption squad investigates allegations of bribery and corruption.",
	"Bribery and corruption undermine the integrity of public institutions.",
	"Nations engage in cyberwarfare to gain an advantage over their adversaries.",
	"Planting the seeds of success requires patience and hard work.",
	"The unfair policy sowed the seeds of discontent among the employees.",
	"Economic disparity planted the seeds of revolution in the society.",
	"He decided to go back to his roots and reopen his grandfather's bakery.",
	"Understanding the root of a program is crucial for effective troubleshooting.",
	"After years of traveling, they're putting down some roots by buying a house.",
	"The movement's strength lies in its grassroots supporters.",
	"She is a budding artist with a lot of potentials.",
	"The company is branching out into new directions with its technology division.",
	"We need to prune back the bushes to allow for new growth.",
	"After years of research, the team is now reaping the rewards of their hard work.",
	"The tree sheds leaves every autumn to prepare for winter.",
	"The company had to shed employees to cope with financial losses.",
	"He shed his inhibitions and danced freely at the party.",
	"He managed to shed weight by adopting a healthier lifestyle.",
	"The media built up the young footballer so much that expectations were sky-high.",
	"In negotiations, we often come up against a brick wall when discussing financial terms.",
	"It feels like the floor can give way beneath your feet when you faint.",
	"With the recent shortages, prices for basic goods have gone through the roof.",
	"If she finds out I'm not going to college, my mom will hit the roof.",
	"The market downturn presented us with a window of opportunity to invest.",
	"When deadlines are tight, my exercise routine goes out of the window.",
	"Lauren towers above all her classmates in terms of academic achievement.",
	"His decision to drop out of college closed a lot of doors for him career-wise.",
	"Acquiring new skills can open doors to exciting career opportunities.",
	"We should not close the door on discussions that could lead to breakthroughs.",
	"He got his job through the back door, thanks to his family connections.",
	"Major decisions were made behind the doors of the executive meeting room.",
	"Continuous learning provides the key to ongoing professional development.",
	"The freezing weather made it difficult to stay outside for long.",
	"The weather turned hot, prompting us to seek shade.",
	"The windy conditions made it difficult to walk against the breeze.",
	"The oppressive heat made it unbearable to stay outdoors.",
	"The room was stifling, lacking any flow of fresh air.",
	"The deluge after the storm caused widespread flooding.",
	"When it started chunking it down, we ran for cover.",
	"The humid weather made the air feel thick and uncomfortable.",
	"The recent scandal has created a climate of distrust within the company.",
	"The organization is undergoing a climate of change to adapt to new market trends.",
	"In the current climate of technological advancement, staying updated is crucial.",
	"The economic climate has made it challenging for startups to secure funding.",
	"The positive financial climate has encouraged investment in new technologies.",
	"The moral climate of society greatly influences the behavior of its citizens.",
	"The receptionist gave me a frosty welcome when I arrived.",
	"The politician faced a storm of abuse after the scandal was revealed.",
	"Their relationship was a whirlwind, moving quickly from acquaintances to partners.",
	"They had a whirlwind romance, marrying just months after they met.",
	"The CEO thundered against the new regulations during the meeting.",
	"The performer was greeted with thunderous applause as she took the stage.",
	"The forecast predicts thundery showers later this afternoon.",
	"The winds of change are blowing through the industry, leading to new innovations.",
	"The winds of democracy are sweeping across the nation, ushering in a new era of governance.",
	"The winds of discontent are stirring among the population, leading to widespread protests.",
	"The region depends on the annual rainfall to sustain its agriculture.",
	"The arid landscape is challenging for farming without irrigation.",
	"The tundra is a vast, cold landscape where only the hardiest species can survive.",
	"The coniferous forest is teeming with evergreen trees that thrive in cold climates.",
	"The deciduous trees shed their leaves in autumn, creating a colorful landscape.",
	"The paddy fields stretch as far as the eye can see, a testament to the region's rice farming.",
	"Farmers tend their crops meticulously to ensure a good harvest.",
	"The country has developed a robust technology sector, leading the world in innovation.",
	"We honor our ancestors by preserving their traditions and stories.",
	"The pioneer family settles in the untamed wilderness, starting a new life.",
	"On our trip, we wanted to get off the beaten track and explore lesser-known areas.",
	"The country's economy heavily relies on the tourist sector, attracting millions of visitors annually.",
	"Discerning travelers look for unique and authentic experiences rather than typical tourist attractions.",
	"National parks protect natural landscapes and provide a sanctuary for wildlife.",
	"Exploring the virgin forests of the Amazon is an adventure into untouched wilderness.",
	"Adventure seekers travel the world looking for the next thrill.",
	"Tourists often look for experiences that are something out of the ordinary, beyond the usual sightseeing spots.",
	"Spending time in nature helps me recharge and face new challenges.",
	"The new waterfront development includes a park and restaurants overlooking the bay.",
	"The view from the mountain top was absolutely stunning.",
	"The hotel offers unbeatable views of the city skyline at night.",
	"Our weekend rambles through the countryside are a perfect escape from city life.",
	"The national park offers several trails for hikes that range from easy to challenging.",
	"The scenic drive along the coast offers breathtaking views of the ocean.",
	"Ecotourism promotes responsible travel to natural areas, conserving the environment and improving the well-being of local people.",
	"The tour takes you through the heartland of the country, showcasing its true cultural essence.",
	"We booked a scheduled flight to Paris since it offered the most convenient timings.",
	"For our group vacation, we're considering a charter flight for more privacy and flexibility.",
	"The all-inclusive resort offers good value for money, including meals, accommodation, and activities.",
	"The hotel charges a cancellation fee if the reservation is canceled less than 48 hours before arrival.",
	"The holiday package includes airport transfers to and from the hotel.",
	"A shuttle bus service is available for guests to travel between the hotel and downtown.",
	"Choosing an all-inclusive resort means all your meals, drinks, and many activities are covered in the price.",
	"We took a ferry to cross the channel to the island, enjoying scenic views along the way.",
	"The ferry crossing to the mainland was smooth and offered beautiful ocean views.",
	"Going on a cruise allows you to visit multiple destinations while enjoying luxurious onboard amenities.",
	"Our trip to the Maldives was the holiday of a lifetime, filled with unforgettable experiences.",
	"On the cruise, we opted for a shared cabin to save on costs without compromising comfort.",
	"The best views on the ferry are from the upper deck, where you can see the horizon.",
	"We found our seats in the third carriage of the train, which was designated for quiet travel.",
	"Fortunately, we booked a through train from Paris to Berlin, avoiding any transfers.",
	"Getting around the city is easiest by subway, thanks to its extensive network.",
	"Be sure to ask about any extras when booking your holiday package, like guided tours or spa treatments.",
	"Staying in a self-catering apartment lets you come and go as you please, offering more flexibility during your vacation.",
	"Camping under the stars offers a unique connection with nature that you can't get from a hotel stay.",
	"Our self-catering cottage by the lake offers the perfect mix of privacy and home comforts.",
	"We rented a mountain chalet for our ski holiday, complete with a fireplace and stunning views.",
	"Staying in a guest house gave us a more authentic and personal experience than a large hotel.",
	"The historic inn we stayed at was known for its traditional cuisine and warm hospitality.",
	"We chose the half board option at the resort, which included breakfast and dinner, giving us the flexibility to explore local eateries for lunch.",
	"Opting for full board meant all our meals were taken care of at the hotel, simplifying our daily planning.",
	"In many countries, pedestrians have the right of way at designated crossings.",
	"The impatient driver kept sounding his horn at the traffic ahead.",
	"Drink-driving is severely punished due to its potential to cause harm.",
	"The city has seen an increase in hit-and-run incidents, prompting a public safety campaign.",
	"Speeding violations add penalty points to your driving record, which can lead to a license suspension.",
	"Before selling a used car, it must be certified as roadworthy to ensure it is safe for operation.",
	"Driving with bald tires is dangerous and increases the risk of accidents.",
	"A major accident on the highway caused a long tailback, delaying traffic for hours.",
	"City centers often face congestion during peak hours, making commuting challenging.",
	"To reduce congestion, the city implemented a congestion charge for drivers entering the central area.",
	"Drivers must pay a toll to use the bridge, which funds its maintenance and operations.",
	"The icy roads led to a multi-car pile-up on the interstate, causing extensive delays.",
	"Traffic was diverted to alternative routes due to roadworks on the main highway.",
	"Cars parked illegally may be clamped, requiring owners to pay a release fee.",
	"The car skidded on the icy road and narrowly avoided hitting a tree.",
	"A head-on collision between two vehicles caused traffic to halt on the highway.",
	"After landing the new job, I am rolling in it.",
	"They're working overtime to make ends meet.",
	"Things are a bit tight at the moment, so we're cutting back on luxuries.",
	"I sent the money via an electronic transfer.",
	"Can you put the dinner on low heat?",
	"The credit card offers an APR of 5%.",
	"Can you get the report out by tomorrow?",
	"Many people prefer contactless payments for their convenience.",
	"She received a lump sum as her retirement package.",
	"He invests mainly in tech stocks and shares.",
	"The insurance policy will cover all medical expenses.",
	"Governments worldwide are focusing on sustainable development goals.",
	"There are encouraging signs that the economy is recovering.",
	"The new policy is starting to take root and show results.",
	"The country aims to achieve economic growth through innovation.",
	"Development grants are crucial for supporting new research initiatives.",
	"The country is pursuing policies to increase renewable energy usage.",
	"Efforts are underway to improve access to clean water in rural areas.",
	"Individuals are finding innovative ways to repay debt more efficiently.",
	"Alleviating debt through relief programs can provide a fresh start for many.",
	"Restrictive practices in trade can harm global economic relationships.",
	"Trade wars often result in higher prices for consumers.",
	"New regulations were imposed to enhance online privacy.",
	"Countries in the monetary union share a common currency to facilitate trade.",
	"International intervention helped to stabilize the region.",
	"The revolution aimed for a regime change but faced strong resistance.",
	"Political unrest led to widespread protests across the nation.",
	"Reports of ethnic cleansing have drawn international condemnation.",
	"Conflict resolution efforts are underway to bring peace to the region.",
	"The nation is waging war on corruption to foster economic growth.",
	"The candidate's campaign focused on healthcare reform.",
	"The country's naval fleet is being modernized to enhance maritime security.",
	"The corporation was accused of bending the rules to avoid taxes.",
	"By dumping waste illegally, the factory contravened environmental laws.",
	"The company infringed a law by not paying minimum wage.",
	"The legislative body voted to impeach the president for misconduct.",
	"Allegations of corruption led to efforts to impeach the governor.",
	"The defendant decided to lodge an appeal against the court's decision.",
	"The higher court upheld the verdict, leaving no room for further appeals.",
	"Tampering with evidence is a serious crime that perverts the course of justice.",
	"The court's decision in this case will set a precedent for future similar cases.",
	"The court decided to grant custody to the mother based on the child's best interests.",
	"The company sought to annul the agreement due to breach of contract.",
	"The marriage was annulled after it was discovered to be fraudulent.",
	"Legislators are working to amend the law to include more protections for workers.",
	"The executive was investigated for insider trading after selling shares before a major announcement.",
	"The witness was accused of perjury after contradicting earlier statements.",
	"New laws have been enacted to address the issue of stalking.",
	"The intruder was arrested for trespass after entering private property without permission.",
	"The majority of citizens are law-abiding and respect the legal system.",
	"Frustrated with the system, he decided to take the law into his own hands.",
	"The new manager laid down the law on her first day, setting strict guidelines for the team.",
	"Despite team protocols, he acted as a law unto himself, ignoring agreed-upon procedures.",
	"From its foundation, the UN has been dedicated to global improvement.",
	"They make use of a slogan to inspire the integration of a particular social group into society.",
	"Members of the political movement go on a march to demonstrate their solidarity.",
	"They have undertaken to support any programme that benefits the community.",
	"Some of the issues are undeniably delicate and require careful consideration.",
	"The participants showed more unity than is customary at such meetings.",
	"Environmental activists decided to lobby MPs to advocate for more stringent environmental policies.",
	"All that's needed is that the petition is properly set out and submitted to the authorities.",
	"The Speaker presides over the session from the Speaker's chair in the assembly.",
	"The expert was asked to offer observations on the new policy proposal.",
	"The parliament will consider all substantive petitions submitted by the public.",
	"The new policies aim to improve healthcare accessibility for all citizens.",
	"The project crosses departmental boundaries, involving multiple teams.",
	"The oversight committee shadows the work of government departments to ensure transparency.",
	"The research team's wide-ranging expertise contributed significantly to the study's success.",
	"The UK constitution, while unwritten, shapes the country's governance and law.",
	"The denial of basic services to the community sparked widespread protests.",
	"Efforts are underway to lift people out of extreme poverty by providing educational opportunities.",
	"After losing his job, he found himself in a state of penury, struggling to afford basic necessities.",
	"Human poverty is not just about lack of income but includes access to services like healthcare and education.",
	"The clinic provides supplements and nutritional advice to malnourished children.",
	"The literacy levels in the region have improved significantly due to the new educational programs.",
	"The charity focuses on aiding children from deprived backgrounds to ensure they have equal educational opportunities.",
	"The area was classed as a high-priority zone for receiving aid due to its economic conditions.",
	"The neighborhood is known for its affluence, with many luxurious homes and upscale shops.",
	"The impoverished village received new funding for a clean water project.",
	"Despite working full-time, he is living from hand to mouth due to high living costs.",
	"Since the factory closed, money has been tight for many families inthe town.",
	"We'll need to tighten our belts this year to save for the home renovation.",
	"A broadcast journalist must effectively convey news stories on television and radio to engage the audience.",
	"Citizen journalism allows ordinary individuals to report news and share stories from their perspectives.",
	"Pressure groups play a pivotal role in influencing public opinion and shaping policy decisions.",
	"Social media platforms allow individuals to air their views on a wide range of issues.",
	"Companies often hold press conferences to announce new products or address public concerns.",
	"Companies are always seeking publicity to enhance their brand image.",
	"Politicians often use soundbites to convey their messages more effectively.",
	"She spent the entire afternoon hunting for the perfect birthday gift.",
	"Researchers are tapping useful sources to gather data for their study.",
	"The team is monitoring the system's performance to prevent any downtime.",
	"The candidate bought additional airtime to reach more voters before the election.",
	"Celebrities often have trouble with paparazzi invading their privacy.",
	"The reporter landed an exclusive interview with the elusive artist.",
	"The news about the discovery broke early in the morning.",
	"The newspaper was sued for libel after publishing false allegations.",
	"He won the lawsuit for defamation of character against the magazine.",
	"She was wrongly accused of stealing the documents.",
	"The journalist's muck-racking article exposed corruption in the government.",
	"After years of research, the team's triumph was developing a new vaccine.",
	"The occurrence of such events has become increasingly rare.",
	"The chef uses only high quality ingredients for his dishes.",
	"Their innovative approach to marketing has doubled their sales.",
	"The quality of their craftsmanship is unsurpassed in the industry.",
	"This technology leaves other competitors standing.",
	"Her performance left all others in the shade.",
	"This product is good value for money, offering high quality at a low price.",
	"The prices have hit rock-bottom, making it the best time to buy.",
	"Prices have been slashed across the board for the holiday sale.",
	"The flea market was full of bargains galore for vintage clothing.",
	"Customers can enjoy a 20% discount on all electronics this weekend.",
	"The hotel promises unparalleled luxury and comfort for its guests.",
	"Take a day off to pamper yourself at the spa.",
	"Indulge yourself with a luxurious vacation this year.",
	"They hosted a sumptuous banquet for their wedding anniversary.",
	"The opulent decor of the mansion impressed every visitor.",
	"After winning the lottery, they lived in the lap of luxury.",
	"The new diet has scientific backing, showing it can significantly reduce health risks.",
	"The ergonomically designed chair reduces back pain during long working hours.",
	"This method is proven to increase productivity.",
	"The laboratory is equipped with state-of-the-art technology.",
	"Regular exercise can make us more attractive and healthy.",
	"Her unique style makes her stand out in the crowd.",
	"This stunning dress is guaranteed to turn heads at the party.",
	"The mystery novel was tantalizingly close to revealing the murderer.",
	"The magazine's glossy cover caught her eye.",
	"She looked radiant on her wedding day.",
	"The new movie was advertised on billboards across the city.",
	"They handed out flyers for the concert in the town square.",
	"Movie trailers give a sneak peek of the film's highlights.",
	"The message of love was spelled out in the sky with sky-writing.",
	"The promoter wore a sandwich board to advertise the new cafe.",
	"The company's logo was designed to be memorable and distinctive.",
	"Pop-ups on the website advertise the latest sales.",
	"The celebrity gave a plug for the charity event during the interview.",
	"We use instant messaging for quick communication between team members.",
	"Chat rooms allow users from all over the world to discuss various topics.",
	"Newsgroups were once popular for sharing news and information on specific interests.",
	"Social networking sites have revolutionized the way we connect with friends and family.",
	"Companies often host webinars to educate customers about their products.",
	"E-commerce has made shopping more convenient and accessible.",
	"E-books offer a portable and eco-friendly alternative to traditional books.",
	"E-learning platforms enable students to study from anywhere in the world.",
	"Accessing online resources has become integral to modern research.",
	"She spent the evening browsing through various online stores for gifts.",
	"Surfing the web is a common way to find information quickly.",
	"The website features graphic images to enhance its visual appeal.",
	"The language learning app includes sound files to aid pronunciation.",
	"She sent the report via email with several attachments.",
	"File-sharing platforms facilitate the exchange of large files over the internet.",
	"Online gaming has become a popular form of entertainment among teenagers.",
	"Many people are concerned about rising ISP charges for internet access.",
	"Always keep your contact details up-to-date on professional networking sites.",
	"Her email was hacked, compromising her personal information.",
	"Users can download the software directly from the website.",
	"She decided to upload her photography portfolio to an online gallery.",
	"My inbox is flooded with spam every day.",
	"Filtering out junk emails has become a necessary daily task.",
	"Social media can be addictive, leading to hours of wasted time.",
	"Websites use cookies to remember your preferences and login details.",
	"The forum has a strict policy against posting offensive material.",
	"Parental control software can help monitor and restrict children's online activities.",
	"She bookmarked her favorite websites for easy access.",
	"I decided to subscribe to the digital edition of the newspaper.",
	"Email filters help screen out spam from important messages.",
	"The company's server crashed, causing a temporary loss of data.",
	"The website was down for maintenance for two hours yesterday.",
	"Installing anti-virus software is essential to protect your computer from malware.",
	"The email bounced because the recipient's inbox was full.",
	"She regularly posts updates about her life on social media.",
	"The newspaper's obituaries section commemorates the lives of individuals who have recently passed away.",
	"The editorial in today's paper calls for urgent action on climate change.",
	"The magazine's cover featured a renowned artist this month.",
	"She found her new apartment through the classified ads in the local newspaper.",
	"The Sunday edition of the newspaper comes with various supplements, including a lifestyle section.",
	"The magazine's feature on sustainable living offered practical tips for reducing waste.",
	"Readers often turn to the agony columns for advice on personal issues.",
	"The magazine's agony aunt provides compassionate advice to readers' letters.",
	"The newspaper boasts a circulation of over one million copies daily.",
	"Researchers publish their findings in scientific journals.",
	"The community center sends out a monthly newsletter to keep residents informed.",
	"Tourists are given a pamphlet that highlights the main attractions of the city.",
	"The company issued a press release announcing the launch of its new product.",
	"Local shops distribute leaflets to advertise sales and events.",
	"Travel agencies use brochures to showcase holiday destinations.",
	"Universities provide prospectuses to give potential students an overview of courses and facilities.",
	"A flyer was posted in the neighborhood to announce the upcoming garage sale.",
	"The health clinic provides a booklet on nutrition and wellness to its patients.",
	"Each employee is given a manual outlining company policies and procedures.",
	"I scheduled an appointment with my primary care doctor for a routine check-up.",
	"Physicians play a crucial role in diagnosing and treating illnesses.",
	"The doctor made a home visit to assess the patient's condition.",
	"The clinic hired a locum to cover for the surgeon who was on vacation.",
	"She was rushed to the hospital with an acute condition that required immediate attention.",
	"Managing a chronic disease often requires lifestyle changes and ongoing care.",
	"After the initial diagnosis, she was referred for secondary care to see a specialist.",
	"Patients with complex health issues are often referred to specialists for further evaluation.",
	"The surgeon performed a transplant to replace the damaged organ.",
	"Ophthalmologists specialize in eye health and can perform surgeries when needed.",
	"Cardiologists diagnose and treat conditions related to the heart and blood vessels.",
	"Psychiatrists are trained to understand the complex relationship between the mind and body in mental health.",
	"Dermatologists treat skin conditions, ranging from acne to skin cancer.",
	"Gynaecologists focus on women's health, especially the reproductive system.",
	"Obstetricians specialize in pregnancy and childbirth, providing care during and after pregnancy.",
	"Paediatricians care for children's health, from infancy through adolescence.",
	"Anaesthetists play a critical role in surgery by ensuring patients are safely anesthetized.",
	"Many people seek alternative medicine for treatments that are outside conventional medical practices.",
	"Complementary medicine is used alongside conventional treatments to improve patient outcomes.",
	"Acupuncturists use thin needles to stimulate specific points on the body to relieve pain.",
	"Chiropractors specialize in treating musculoskeletal issues through manual adjustment of the spine.",
	"Homeopathic doctors use highly diluted substances to trigger the body's natural healing processes.",
	"Aromatherapists use essential oils for therapeutic purposes to improve physical and emotional well-being.",
	"Access to quality healthcare is essential for maintaining a healthy society.",
	"National Insurance contributions are mandatory for working individuals to fund public services.",
	"The National Health Service provides free healthcare to residents in the country.",
	"My family doctor knows my health history and provides personalized care.",
	"General practitioners are often the first point of contact for patients seeking medical advice.",
	"The surgery was successful, and the patient is expected to make a full recovery.",
	"I visited the clinic for a routine health check-up.",
	"The prescription charge is a nominal fee for medication dispensed by the pharmacy.",
	"Various insurance schemes are available to cover medical expenses and provide financial security.",
	"He's been feeling off-colour all week, possibly due to stress at work.",
	"She's been out of sorts lately, so she decided to take a few days off.",
	"After feeling poorly for several days, he finally visited the doctor.",
	"She's been fighting off a cold and trying to rest as much as possible.",
	"He's gone down with the flu and won't be able to attend the meeting.",
	"She came down with a fever last night and is taking a sick day.",
	"Many people suffer from allergies during the spring season.",
	"My arm hurts where I got the vaccine yesterday.",
	"After the long hike, my legs ached for days.",
	"As he gets older, he's experiencing more aches and pains.",
	"After the fall, she had several cuts and bruises but nothing serious.",
	"The cut on my hand is stinging, especially when it comes into contact with water.",
	"He complained of a throbbing headache that wouldn't go away.",
	"Waking up with a stiff neck, she found it difficult to turn her head.",
	"She twisted her ankle while running and had to stop.",
	"Standing up too quickly, he felt dizzy and had to sit back down.",
	"Feeling feverish, she checked her temperature, which was higher than normal.",
	"Despite the warm room, she felt shivery and wrapped herself in a blanket.",
	"She kept feeling hot and cold, a sign that she might be getting sick.",
	"The stress from work left him sleepless, tossing and turning all night.",
	"The strong smell in the room made her feel nauseous.",
	"After hearing the news, he was trembling with a mix of fear and anger.",
	"With a cold, she felt completely bunged up and couldn't breathe properly.",
	"It took him weeks to get over the flu, but he's finally feeling better.",
	"She's recovering from surgery and needs plenty of rest and care.",
	"After a week of being ill, he's finally on the mend.",
	"She feels she's over the worst of the illness and is slowly improving.",
	"With proper care and rest, she'll be back on her feet in no time.",
	"Before taking this medicine, read the instructions carefully to avoid any side effects.",
	"If you have any concerns about the medication, talk to your doctor or pharmacist.",
	"The medication is available in a low-dose form for those with sensitivity.",
	"Regular check-ups are crucial for managing asthma effectively.",
	"Patients with a past history of allergic reactions should inform their doctor before starting any new medication.",
	"Eating disorders require a comprehensive treatment plan that addresses both psychological and nutritional needs.",
	"Gastrointestinal disease can significantly impact a person's quality of life and requires specialized care.",
	"Bowel movements are a key indicator of digestive health.",
	"Patients should report any adverse reactions to medication to their healthcare provider immediately.",
	"Preventative measures like maintaining a healthy diet and regular exercise can reduce the risk of stroke.",
	"Chronic conditions, such as diabetes and heart disease, require ongoing management and care.",
	"Do not exceed the recommended dose of this medication to avoid adverse effects.",
	"The duration of the treatment will depend on the patient's response to the medication.",
	"If you experience any allergic reactions to the medication, seek medical help immediately.",
	"Airborne particles can exacerbate respiratory conditions like asthma.",
	"Changes in the color or consistency of stools can indicate a digestive problem.",
	"Monitoring excrement can provide valuable insights into an individual's health.",
	"Consistent changes in poo can be a sign of dietary or health issues.",
	"Nausea is often a precursor to vomiting and can be caused by various factors.",
	"Vomiting can relieve the body of toxic substances but should not be ignored if persistent.",
	"Disorientation and confusion can be symptoms of a severe illness or reaction to medication.",
	"Fever is a common symptom of many infectious diseases.",
	"Being symptomatic means showing signs of a disease, which can aid in early diagnosis.",
	"She was diagnosed with diabetes after a series of blood tests.",
	"The prognosis after the surgery is positive, with a high chance of full recovery.",
	"The ailing company needed drastic changes to return to profitability.",
	"There's been a rash of flu cases in the community recently.",
	"High fever is often treated with medication to reduce the body temperature.",
	"Excitement about the championship game reached fever pitch as the final match approached.",
	"His jaundiced view of the project was due to his previous failures.",
	"Many soldiers return home carrying the scars of war, both physically and emotionally.",
	"The virus can infect individuals through respiratory droplets from coughs and sneezes.",
	"The manager always has his finger on the pulse, knowing exactly what the customers want.",
	"Traffic was impeded due to the construction work, causing delays.",
	"Dental plaque can lead to tooth decay if not properly cleaned.",
	"High cholesterol levels can clog arteries, increasing the risk of heart disease.",
	"Managing cholesterol levels is crucial for cardiovascular health.",
	"A stroke occurs when blood flow to the brain is interrupted, causing brain cells to die.",
	"Incorporating nutritious foods into your diet can improve overall health and well-being.",
	"Avoiding cholesterol-rich foods is advised for those with heart conditions.",
	"Untreated hypertension can pose a danger to cardiovascular health.",
	"Fibre is essential for digestive health and can help prevent constipation.",
	"Eating a high-fibre diet can lower the risk of heart disease and diabetes.",
	"Lentils are a great source of protein and fibre, making them a healthy addition to any diet.",
	"Starting your day with oatmeal can provide you with sustained energy and essential nutrients.",
	"Porridge is a comforting and nutritious breakfast option, rich in fibre and minerals.",
	"Regular exercise is key to maintaining cardiovascular health and preventing heart disease.",
	"Diabetics need to monitor their blood sugar levels closely to manage their condition effectively.",
	"Diabetes affects the body's ability to process glucose, requiring careful dietary and lifestyle management.",
	"Glucose is a vital energy source for the body's cells but must be maintained within a healthy range.",
	"Insulin is a hormone that helps regulate blood sugar levels by facilitating the uptake of glucose into cells.",
	"Engaging in regular physical activity is an effective way to burn calories and improve overall health.",
	"Having a sporty lifestyle involves incorporating various forms of physical activity into your daily routine.",
	"Metabolism is the process by which the body converts food into energy, and its efficiency can vary between individuals.",
	"Body Mass Index (BMI) is a measure used to determine if a person's weight is in a healthy range for their height.",
	"She is intent on improving her fitness level by incorporating more exercise into her lifestyle.",
	"A brisk walk in the morning can kickstart your metabolism and energize you for the day.",
	"I scored an own goal when I told my boss it had only taken me a day to write the report.",
	"My boss always seems to be moving the goalposts.",
	"The new EU law aims to provide a level playing field for all member states.",
	"She is too young to be considered a candidate for the job.",
	"The two main parties in the election are still neck and neck in the opinion polls.",
	"Politicians often skate around a subject.",
	"The students all sailed through their exams.",
	"The city's economy was historically dominated by heavy industry, such as steel production and shipbuilding.",
	"Light industry, such as electronics manufacturing, plays a vital role in the region's economic development.",
	"The manufacturing industry, including automotive and textile sectors, is a major employer in the area.",
	"The service industry, ranging from banking to hospitality, has seen significant growth over the past decade.",
	"Companies in the high-technology sector, such as biotech and software firms, are leading innovation.",
	"Low-technology industries, including agriculture and traditional manufacturing, remain crucial for many economies.",
	"Startups often rely on cutting-edge technology to disrupt established markets and gain a competitive edge.",
	"Despite the rise of digital platforms, conventional technology like print media still has a significant audience.",
	"The privatisation of previously state-owned enterprises has sparked debate over its impact on service quality and employment.",
	"The government's decision to proceed with the nationalisation of key industries has been met with mixed reactions.",
	"State ownership of utilities ensures that essential services like water and electricity are accessible to all.",
	"Public-private partnerships have been instrumental in developing infrastructure projects that otherwise would have been unfeasible.",
	"The government provides a subsidy to farmers to support them during periods of low market prices for crops.",
	"Inward investment by foreign companies has been a major driver of economic growth in developing countries.",
	"Many garment workers are paid on piecework, earning a fixed amount for each item they produce.",
	"Zero hour contracts offer flexibility for employers but can result in unpredictable income for employees.",
	"The international community continues to fight against child labour, advocating for education and safe working conditions for minors.",
	"Trade union representation is essential for negotiating better wages and working conditions for employees.",
	"Sweatshops, where workers are subjected to poor conditions and low wages, are still prevalent in some industries.",
	"Retraining programs are crucial for workers who need to adapt to the changing demands of the job market.",
	"Reskilling efforts focus on equipping employees with new skills that are in demand in today’s economy.",
	"Multinationals often face criticism for their business practices in developing countries, despite bringing in investment.",
	"The company launched a cost-cutting exercise to improve profitability by reducing overhead expenses.",
	"The tech company decided to relocate its headquarters to a city with a more vibrant tech ecosystem.",
	"To meet the surge in demand, the manufacturer had to switch production to high-efficiency models.",
	"Electronic devices are made up of numerous small components, each playing a critical role in the device's functionality.",
	"The furniture comes flat-packed and needs to be assembled at home.",
	"Many companies are now integrating digital technology to improve their operational efficiency.",
	"The digital clock on the wall shows it's almost time for our meeting.",
	"Despite the rise of digital, some artists prefer analogue equipment for its warmer sound.",
	"Connecting to wi-fi at the cafe, she began her freelance work for the day.",
	"Satellite communications enable people in remote areas to access the internet.",
	"The GPS system guided us through the city to reach our destination without getting lost.",
	"I rely on my SATNAV to find the quickest routes during my road trips.",
	"Advances in biotechnology have led to the development of new and effective vaccines.",
	"Farmers are increasingly planting disease-resistant crops to ensure a better yield.",
	"Artificial intelligence is transforming industries by automating complex processes.",
	"The ergonomics of the workplace significantly affect employee productivity and comfort.",
	"This ergonomically designed chair provides both comfort and support for long hours of work.",
	"My new headphones connect to my phone via Bluetooth for a wireless listening experience."
]


with open('notes.html', encoding='utf-8') as html:
	selector = Selector(text=html.read())
	spans = selector.css('span::text')
	for sentence in sentences:
		words = sentence.split(' ')
		words = [x.replace('.', '').replace(',', '').lower() for x in words if len(x) > 4]
		print(sentence)
		for word in words:
			match = spans.re_first(rf'{word}')
			if match:
				print(f'\t{match}')